### PR TITLE
Enable the installation of poetry requirements

### PR DESCRIPTION
**Pull request by justincmoy**
**What does your PR do?**
If `dags.installPoetryRequirements` is specified, process Python DAGs dependencies using [poetry](https://python-poetry.org/).

## Checklist

- [x] Commits are [signed](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#sign-your-work)
- [x] Commits are [squashed](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#squash-commits) (if appropriate)
- [x] Chart [version bumped](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#versioning)
- [x] Chart [documentation updated](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#documentation)
- [x] Passes [linting](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#linting)

### CODE REVIEW

**Comment by gsemet** [comment]
I would agree. @thesuperzapper do you ?

**Comment by thesuperzapper** [comment]
@gsemet Please wait until I have merged 8.0.0 as I have moved the Pip install into a seperate location, so it will require a redesign to install non-pip packages.

**Comment by gsemet** [comment]
That’s what I thought ;)

**Comment by thesuperzapper** [comment]
@justincmoy thanks for your work!

However, since we have removed `dags.installRequirements` after version `8.0.0` for the reasons stated in the `UPGRADE.md`, I don't think we will implement this feature as you have proposed.

Feel free to raise an issue and discuss with the community if you feel its and important feature.

**Comment by justincmoy** [comment]
> @justincmoy thanks for your work!
> 
> However, since we have removed `dags.installRequirements` after version `8.0.0` for the reasons stated in the `UPGRADE.md`, I don't think we will implement this feature as you have proposed.
> 
> Feel free to raise an issue and discuss with the community if you feel its and important feature.

Thanks for the update! I think there's value in keeping the dag requirements with the dags, but I understand [the reasoning behind the removal](https://github.com/airflow-helm/charts/blob/main/charts/airflow/UPGRADE.md#removed-features). We'll discuss how we want to proceed and push any changes we make to the helm chart.

**Pull request closed without merging**
