### PR TITLE
feat: add support for `DaskExecutor`

### LINKED ISSUE #815: Feature - add dask executor support
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Motivation

I would like to use this chart as part of an step in the efforts of operationalizing [godon](https://github.com/cherusk/godon) stack.

I find dask executor is a great option, in my mind even superior to the other executors. In other words I do not want to use the othe executors for various reasons.

### Implementation

As several executor "backends" are already supported by this chart, taking up dask executor should not be too great of a lifting.

### Are you willing & able to help?

- [X] I am able to submit a PR!
- [X] I can help test the feature!

### PR DESCRIPTION
**Pull request by cherusk**
## What issues does your PR fix?

- fixes #815

## What does your PR do?

This PR brings about a new Airflow executor backend on Dask/Distributed cluster.

### For all Pull Requests

- [x] Commits are [signed off](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#sign-your-work)
- [x] Commits have [semantic messages](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#semantic-commit-messages)
- [x] Documentation [updated](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#documentation)
- [x] Passes [ct linting](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#linting)

### CODE REVIEW

**Comment by cherusk** [comment]
@thesuperzapper this should be it. Please give it a gander for now.

I've not tested this outside of this PR yet.

**Comment by cherusk** [comment]
@thesuperzapper @gsemet could you please prioritize this up? Thanks!

**Comment by cherusk** [comment]
I've as interim solution pushed the altered chart to https://github.com/users/cherusk/packages/container/package/airflow

**Comment by thesuperzapper** [comment]
@cherusk thanks for the PR, but it looks like as of Airflow 2.9.0, the upstream project has decided to stop supporting `DaskExecutor`:

- https://github.com/apache/airflow/pull/35965

I understand that will be frustrating!

**Pull request closed without merging**
