### PR TITLE
Add keda autoscaler support

### PR DESCRIPTION
**Pull request by dstandish**
**What does your PR do?**

This PR adds support for KEDA.

KEDA v2.0.0 allows scaling of StatefulSets, which makes it compatible with this helm chart.

Ther are two things that I'd like to call to your attention.

**Creds logic for the ScaledObject**

I had some trouble finding a good way to use existing config structure and allow local postgres, external db, and connection properties but I think I worked out a decent solution.

The first issue was that currently the chart expects urlencoded database properties like `&sslmode=disable` This assumes we'll use a URI for all database connections.

So I tried to use URI format for ScaledObject.

But I found there is no way to assemble the full connection URI, because the chart assumes the password comes from a secret independently (as opposed to a secret containing full URI).   And apparently you can't really concat env vars that come from secrets in the helm chart (which I guess is why the chart uses the _CMD env vars, but this won't work with the ScaledObject definiton).  So, this forces me to provide the database params individually (as opposed to URI).  Which brings back to the first problem -- the properties are given as urlencoded params.

But so my solution was to simply add sslmode as optional config under `workers.keda`; this is the only extra param available within postgres trigger, and in mysql there are no extra params.

It would be safer to use URI secret because user has full control and template doesn't need to worry about the logic.  But that's inconsistent with the chart.

Anyway, guidance on this would be appreciated.

**Inclusion of KEDA as dependency**

I did not add keda as dependency initially.   Initially I assumed you would install keda independently.

On the one hand it is desirable to install the keda components independently, so that it could be used with multiple airflow instances in the same cluster.

On the other hand, including keda as a dependency simplifies installation.

A third option would be to specify `keda` namespace for the keda components, which would just require that the user create a keda namespace (i _think_ this is possible).  Feedback on this one appreciated as well.

Thanks

### CODE REVIEW

**Comment by dstandish** [comment]
Lint check is failing cus missing repo:
```
Error: no repository definition for https://kedacore.github.io/charts. Please add the missing repos via 'helm repo add'
```

**Comment by gsemet** [comment]
Hi. Seems a very good idea and maybe could help lot of users, but probably we do not want direct dependency on keda on the main chart. But, we can create a derivative chart (ex: `airflow-helm/keda-chart`)

**Comment by dstandish** [comment]
For what it's worth, the dependency is optional I think.  That was the intention anyway.  In any case it will only install if enabled.

Another option like I tried to mention is to remove the dependency and just provide instructions in readme when keda desired.  This is what is done in astro chart and Apache/airflow chart.

Lemme know your thoughts.

**Comment by thesuperzapper** [comment]
@dstandish I have raise a new issue for KEDA support if your interested in contributing it!

I think a large part of it will be docs.

https://github.com/airflow-helm/charts/issues/103

**Pull request closed without merging**
