### PR TITLE
[Git] shallow clonning

### LINKED ISSUE #60: [GitSync and GitClone] Use shallow clone and single branch
**What is your feature request?**

For the Git Sync and Git Clone it would be helpful to use shallow clone (only clone the blobs and not the entire history) this goes with the single branch option.
https://git-scm.com/docs/shallow
https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt

**What alternatives have you considered?**
Moving DAGs out of the monorepo into a separate repository.

### PR DESCRIPTION
**Pull request by povode**
What issues does your PR fix?

- fixes #60

What does your PR do?

Improve git clone by only cloning the blobs in a single branch and not the complete repo and history

## Checklist

- [x] Commits are [signed](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#sign-your-work)
- [x] Commits are [squashed](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#squash-commits) (if appropriate)
- [x] Chart [version bumped](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#versioning)
- [x] Chart [documentation updated](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#documentation)
- [x] Passes [linting](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#linting)

### CODE REVIEW

**Comment by gsemet** [comment]
can you put this as optional and put the depth as parameter. I agree the default should be that it is enabled and depth put to 1, but I prefer if there is option to enable it back for any reason

**Comment by povode** [comment]
ops, completely forgot about this one, sorry for the delay I'll try to finish it this week.

**Comment by thesuperzapper** [comment]
@povode dont worry, I have moved the chart to a new git-sync system

**Comment by thesuperzapper** [comment]
This is now the default behaviour after version `8.0.0`, but with a different git-sync sidecar.

**Pull request closed without merging**
