### PR TITLE
release 8.0.1

### LINKED ISSUE #97: Validation helper makes bad assumption
Thanks for pushing out the new version of the chart!

**What is the bug?**

The validation helper, in the case where the executor = CeleryExecutor, makes false assumptions.

The values support an external redis, and implicitly support external celery workers.  I think this validation will need to be removed.

https://github.com/airflow-helm/charts/blob/9ebbfb6f65ad68715d2492f88fc1b7b079f27249/charts/airflow/templates/_helpers/validate-values.tpl#L17-L20

**What are your Helm values?**

We are running celery workers outside the cluster & using an in-cluster redis to broker queues.

```
airflow:
  executor: CeleryExecutor

redis:
  enabled: true

workers:
  enabled: false
```

**What is your Kubernetes Version?**:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

### LINKED ISSUE #98: extraVolumeMounts and extraVolumes parsing error
**What is your question?**

Thank you for the new version!

I was trying to run it adding a couple of extra volumes and extra volume mounts but I'm getting a parsing error.

image

image

The PVCs already exist, am I doing something wrong or is this a bug?

Thank you for your time.

### LINKED ISSUE #99: cannot patch "airflow-upgrade-db" with kind Job: Job.batch "airflow-upgrade-db" is invalid
**What is the bug?**

When trying to modify our Airflow deployment using the latest chart via Terraform, we consistently run into the following error:
```
Error: cannot patch "airflow-upgrade-db" with kind Job: Job.batch "airflow-upgrade-db" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"app":"airflow", "component":"jobs", "controller-uid":"df138fad-f51c-4ed6-a01b-553c39731356", "job-name":"airflow-upgrade-db", "release":"airflow"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume(nil), InitContainers:[]core.Container{core.Container{Name:"check-db", Image:"apache/airflow:2.0.1-python3.8", Command:[]string{"/usr/bin/dumb-init", "--"}, Args:[]string{"bash", "-c", "exec airflow db check"}, WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource{core.EnvFromSource{Prefix:"", ConfigMapRef:(*core.ConfigMapEnvSource)(nil), SecretRef:(*core.SecretEnvSource)(0xc02223d7e0)}}, Env:[]core.EnvVar{core.EnvVar{Name:"DATABASE_PASSWORD", Value:"", ValueFrom:(*core.EnvVarSource)(0xc02223d820)}, core.EnvVar{Name:"REDIS_PASSWORD", Value:"", ValueFrom:(*core.EnvVarSource)(0xc02223d840)}, core.EnvVar{Name:"PYTHONPATH", Value:"/opt/python/site-packages:/opt/airflow/dags/repo", ValueFrom:(*core.EnvVarSource)(nil)}}, Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount(nil), VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(0xc006362730), Stdin:false, StdinOnce:false, TTY:false}}, Containers:[]core.Container{core.Container{Name:"upgrade-db", Image:"apache/airflow:2.0.1-python3.8", Command:[]string{"/usr/bin/dumb-init", "--"}, Args:[]string{"bash", "-c", "exec airflow db upgrade"}, WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource{core.EnvFromSource{Prefix:"", ConfigMapRef:(*core.ConfigMapEnvSource)(nil), SecretRef:(*core.SecretEnvSource)(0xc02223d9a0)}}, Env:[]core.EnvVar{core.EnvVar{Name:"DATABASE_PASSWORD", Value:"", ValueFrom:(*core.EnvVarSource)(0xc02223d9e0)}, core.EnvVar{Name:"REDIS_PASSWORD", Value:"", ValueFrom:(*core.EnvVarSource)(0xc02223da00)}, core.EnvVar{Name:"PYTHONPATH", Value:"/opt/python/site-packages:/opt/airflow/dags/repo", ValueFrom:(*core.EnvVarSource)(nil)}}, Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount(nil), VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(0xc006362780), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:"OnFailure", TerminationGracePeriodSeconds:(*int64)(0xc023915170), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc02175c380), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil)}}: field is immutable
```

**What are your Helm values?**

The values that we merge with `values.yaml` via Terraform are as follows:
```
--- 
dags: 
  gitSync:
    enabled: true
    repo: "${var.airflow_config.github_repository_url}"
    branch: "airflow-test"
    revision: "HEAD"
    syncWait: 60

airflow:
  config:
    AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
  extraEnv:
    - 
      name: PYTHONPATH
      value: "/opt/python/site-packages:/opt/airflow/dags/repo"
  extraPipPackages:
    - "apache-airflow[google]==2.0.1"
    - "SQLAlchemy==1.3.23"

externalDatabase:
  type: ${var.airflow_config.db_type}
  host: ${var.airflow_config.db_host}
  port: ${var.airflow_config.db_port}
  database: ${var.airflow_config.db_name}
  user: ${var.airflow_config.db_user}
  passwordSecret: "${var.airflow_config.db_password_secret}"
  passwordSecretKey: "${var.airflow_config.db_password_secret_key}"

postgresql:
  enabled: false
```

**What is your Kubernetes Version?**:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.7800", GitCommit:"cef3156c566a1d1a4b23ee360a760f45bfbaaac1", GitTreeState:"clean", BuildDate:"2020-12-14T09:12:37Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"dirty", GoVersion:"go1.15.3"}
```

### LINKED ISSUE #101: Flower deployment fails with airflow.extraVolumeMounts set
**What is the bug?**
I am trying to install v8.0.0 of this chart with `airflow.extraVolumeMounts`. I am using the default flower configurations and am getting this error. 
```
Error: YAML parse error on airflow/templates/flower/flower-deployment.yaml: error converting YAML to JSON: yaml: line 203: mapping values are not allowed in this context
```
It looks like adding extraVolumes breaks the yaml. The output renders like
```
          volumeMounts:            
            - name: python-site-packages
              mountPath: /opt/python/site-packages- mountPath: /opt/airflow/dags
              name: synchronised-efs
      volumes:        
        - name: python-site-packages
          emptyDir: {}- name: synchronised-efs
          persistentVolumeClaim:
            claimName: airflow
```

**What are your Helm values?**

airflow:
  extraVolumeMounts:
    - name: synchronised-efs
      mountPath: /opt/airflow/dags

  extraVolumes:
    - name: synchronised-efs
      persistentVolumeClaim:
        claimName: airflow

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
$ helm version
please put the output here
```

### PR DESCRIPTION
**Pull request by thesuperzapper**
This release resolves some of the initial issues that have been uncovered with version `8.0.0`.

I have added a debug value called `helmWait`, which should be enabled when the `--wait` flag is used with `helm install`, to prevent it hanging forever. The reason we created a value for this, is most users are not using the `--wait` flag, and to prevent issues like #99 it is better that the `upgrade-db` job is removed before it is recreated (due to the immutability of Job specs)

- fixes #101
- fixes #99
- fixes #98
- fixes #97

## Checklist

- [X] Commits are [signed](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#sign-your-work)
- [X] Commits are [squashed](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#squash-commits) (if appropriate)
- [X] Chart [version bumped](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#versioning)
- [X] Chart [documentation updated](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#documentation)
- [X] Passes [linting](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#linting)

### CODE REVIEW

**Review by gsemet — APPROVED** [review]

**Comment by gsemet** [comment]
Good work and thank a lot to take the lead on the chart maintainance!

**Comment by thesuperzapper** [comment]
@gsemet more than happy for you to make changes also, lol!

We should really video chat sometime, we could use the airflow slack server: https://apache-airflow-slack.herokuapp.com/

**Comment by gsemet** [comment]
Sure ! I would be available Tuesday afternoon (Central Europe time, as I am in France)

**Comment by thesuperzapper** [comment]
@gsemet can you message me on the slack so we can exchange emails!

Search for "Mathew Wicks"

**Pull request merged**
