### PR TITLE
feat: add support to rename Service port for Istio

### PR DESCRIPTION
**Pull request by dansc0de**
## What issues does your PR fix?

- allow service port names to be set for pgbouncer, workers, and web Services. This causes [issues](https://istio.io/latest/docs/reference/config/analysis/ist0118/) with istio service mesh when the service ports do not have the protocol. 

## What does your PR do?

parameterize the airflow values.yaml file with {pgbouncer|workers|web}.service.portName settings, and updates the {pgbouncer|workers|webservere}-service.yaml files with the new setting. Also providing sane default in the service files.

### For all Pull Requests

- [x] Commits are [signed off](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#sign-your-work)
- [x] Commits have [semantic messages](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#semantic-commit-messages)
- [x] Documentation [updated](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#documentation)
- [x] Passes [ct linting](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#linting)

### For releasing ONLY

- [x] Chart.yaml [version bumped](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#versioning)
- [x] CHANGELOG.md updated

### CODE REVIEW

**Comment by aodj** [comment]
@gsemet @thesuperzapper any chance of getting this merged?

**Comment by thesuperzapper** [comment]
@danattatari thanks for the PR, I am trying to understand the rationale behind running the chart inside an istio mesh.

I have made a comment about my thoughts in https://github.com/airflow-helm/charts/issues/510#issuecomment-1044040669.

**Comment by thesuperzapper** [comment]
@danattatari As I raised in https://github.com/airflow-helm/charts/issues/510#issuecomment-1047394953, I think we should instead be dynamically setting the `protocol` field of [`ContainerPort v1`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#containerport-v1-core) (added in K8S 1.18) based off if the `AIRFLOW__WEBSERVER__WEB_SERVER_SSL_CERT` and `AIRFLOW__WEBSERVER__WEB_SERVER_SSL_KEY`configs are set.

**Comment by betmix-matt** [comment]
This would be something very useful for my business. I have to use a Fork of this repository to change the port names so I can run this inside of Istio (a requirement for my business).

**Comment by thesuperzapper** [comment]
@dansc0de thanks for the PR, but we are closing in favor of https://github.com/airflow-helm/charts/pull/854 as it does not require new values to be added.

**Pull request closed without merging**
