### PR TITLE
fix: sync-users for airflow 2.7.0

### PR DESCRIPTION
**Pull request by SamWheating**
## What issues does your PR fix?

- fixes https://github.com/apache/airflow/issues/33635 (which was created in the airflow repo)
- fixes https://github.com/airflow-helm/charts/discussions/771

## What does your PR do?

Updates this import path to be Airflow 2.7.0-friendly

### For all Pull Requests

- [x] Commits are [signed off](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#sign-your-work)
- [x] Commits have [semantic messages](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#semantic-commit-messages)
- [x] Documentation [updated](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#documentation)
- [ ] Passes [ct linting](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#linting)

### For releasing ONLY

- [ ] Chart.yaml [version bumped](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#versioning)
- [ ] CHANGELOG.md updated

### CODE REVIEW

**Comment by VictorAtPL** [comment]
Thank you @SamWheating,

I deployed this modified Helm chart version and it's working fine for last 15 minutes. Will continue monitoring.

**Comment by giancarloromeo** [comment]
@SamWheating: I tried your patch and it works fine.

**Comment by Amar1404** [comment]
Is there any alternative way untill this is implemented.

**Comment by khmelevskiy** [comment]
Hello! when is this issue going to be fixed? this prevents our team from updating the airflow :(

**Comment by thesuperzapper** [comment]
@SamWheating thanks for this!

I will test with Airflow 2.7 and cut a release with this fix shortly.

**Comment by monircefalo** [comment]
Hi @thesuperzapper , i am using Airflow 2.5. still this is happening. Wanted to use Airflow 2.7. Waiting for you fix.
Thanks

**Comment by khmelevskiy** [comment]
hello, please tell me when approximately the merge is planned?

**Comment by thesuperzapper** [comment]
@khmelevskiy about 43 minuets ago!

It's in [version 8.8.0](https://github.com/airflow-helm/charts/releases/tag/airflow-8.8.0) of the chart.

**Pull request merged**
