### PR TITLE
feat: programmatically controlled dags

### PR DESCRIPTION
**Pull request by asosnovsky**
## What does your PR do?

Adds support for programmatically pausing/unpausing of DAGS

### For all Pull Requests

- [X] Commits are [signed off](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#sign-your-work)
- [X] Commits have [semantic messages](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#semantic-commit-messages)
- [X] Documentation [updated](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#documentation)
- [X] Passes [ct linting](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#linting)

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@asosnovsky this is an interesting idea, can you clarify the situations where someone would need/want this functionality?

Additionally, are you sure that every valid dag_id can be stored in a YAML map key? (It might make more sense to store the "controlled" dags in a YAML list of maps, with a key called `dagID` that stores a string value)

**Comment by asosnovsky** [comment]
So I'm managing a system where we have over 10 deployments that require different subsets of dags. Additionally, sometimes engineers forget to turn on/off dags that they were debugging (when random prod issues happen). With this feature (which we already hacked something similar internally) we can reapply the helm chart on a schedule or during new deployments.

**Comment by asosnovsky** [comment]
@thesuperzapper i am not sure I am following your solution... care to share an example?

**Comment by asosnovsky** [comment]
@thesuperzapper do you mean like

```yaml
controlled:
   - dagId: myawesomedag
   - dagId: mycooldag2
     disabled: false
```

**Comment by thesuperzapper** [comment]
> So I'm managing a system where we have lots of deployments that require different subsets of dags. Additionally, sometimes engineers forget to turn on/off dags that they were debugging.

It really seems quite dangerous to use a control loop to force certain dags to be enabled/disabled. There are many situations when you may want to temporarily disable a dag to prevent/fix an issue, and with this, you would be fighting with the controller.

To solve your stated problem of people accidentally leaving dags disabled/enabled, it makes more sense to suggest an upstream change in airflow itself to alert/highlight when an important dag has been left disabled for some period of time. This would be similar to the existing [SLA feature](https://airflow.apache.org/docs/apache-airflow/stable/concepts/tasks.html#slas), but it's not quite the same, as SLAs only apply to enabled dags.

You may want to suggest any ideas/proposals you have around this in the [airflow thread that is discussing a rewrite of the SLA feature](https://github.com/apache/airflow/discussions/21233), or possibly raise your own separate ["airflow improvement proposal"](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals) for a "monitored dags" feature like I described above.

But either way, I don't think I am comfortable adding this "dag controller" feature to the chart as I think it's unsafe (feel free to explain why my thinking is wrong).

**Comment by thesuperzapper** [comment]
> So I'm managing a system where we have lots of deployments that require different subsets of dags. Additionally, sometimes engineers forget to turn on/off dags that they were debugging.

@asosnovsky It really seems quite dangerous to use a control loop to force certain dags to be enabled/disabled. There are many situations when you may want to temporarily disable a dag to prevent/fix an issue, and with this, you would be fighting with the controller.

To solve your stated problem of people accidentally leaving dags disabled/enabled, it makes more sense to suggest an upstream change in airflow itself to alert/highlight when an important dag has been left disabled for some period of time. This would be similar to the existing [SLA feature](https://airflow.apache.org/docs/apache-airflow/stable/concepts/tasks.html#slas), but it's not quite the same, as SLAs only apply to enabled dags.

You may want to suggest any ideas/proposals you have around this in the [airflow thread that is discussing a rewrite of the SLA feature](https://github.com/apache/airflow/discussions/21233), or possibly raise your own separate ["airflow improvement proposal"](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals) for a "monitored dags" feature like I described above.

But either way, I don't think I am comfortable adding this "dag controller" feature to the chart as I think it's unsafe (feel free to explain why my thinking is wrong).

**Comment by asosnovsky** [comment]
@thesuperzapper I don't see how this relates to SLA. It has nothing to do with notifying when a dag takes longer than expected. But I do agree that it can be annoying/dangerous when you try to pause a DAG and it just bounces back after a minute.

Perhaps, if we just dropped the "Deployment" and kept only the "Job" implementation it would make a better compromise. That way, to return to "normal" you would have to use reapply the chart. It's anyways all I actually need, I.e. a clean way to return to the expected original state for a given deployment. If I didn't want someone to modify the DAG states I would just not give them that permission. 

To strengthen the case for this. It's not uncommon (in my experience) for companies to require a special approval process to enable/permanently pause a DAG. Ensuring that there is a programatic way to sync the wanted state for all DAGs (by triggering the job using helm) using a nice infrastructure as code approach is what we use kubernetes for, and not necessarily should expect it from Airflow. (The alternatives I've seen usually involve writing a bash or python script that does the same, or writing a DAG that does the same, which is much less clean than using helm, and tend to have worst audit logs). Plus airflow does provide this feature by allowing users to modify the db dag states (which is what my implementation utilizes).

**Pull request closed without merging**
