### PR TITLE
Allow parens in password

### PR DESCRIPTION
**Pull request by jgilme1**
**What issues does your PR fix?**
    Was getting the following exception in the worker logs for KubernetesExecutor when I had a password like password(withparens
    
```
    [2021-04-12 14:17:25,604] {logging_mixin.py:104} INFO - Running <TaskInstance: gitsynctutorial.print_date 2021-04-12T14:11:53.057909+00:00 [running]> on host gitsynctutorialprintdate.3bbeb001fcf4453d8596711a6e828149
    [2021-04-12 14:17:25,731] {taskinstance.py:1455} ERROR - Cannot execute bash -c 'eval "echo -n "postgresql+psycopg2://airflow:$(eval echo password(withparens | python3 -c "import urllib.parse; encoded_pass = urllib.parse.quote(input()); print(encoded_pass)")@host:5432/airflow""'. Error code is: 1. Output: , Stderr: bash: command substitution: line 1: syntax error near unexpected token `('
```

**What does your PR do?**

Puts the variable of the echo command in quotes so that the bash parsing does not fail

## Checklist

- [x ] Commits are [signed](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#sign-your-work)
- [ x] Commits are [squashed](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#squash-commits) (if appropriate)
- [ x] Chart [version bumped](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#versioning)
- [ ] Chart [documentation updated](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#documentation)
- [ ] Passes [linting](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#linting)

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@jgilme1 why did you close?

**Comment by jgilme1** [comment]
Didn't sign the commit correctly. Will fix and re-open tomorrow.

**Comment by thesuperzapper** [comment]
@jgilme1 You know about force-pushing right, you dont need to close a PR to change whats in it?

**Comment by jgilme1** [comment]
Closed it so you wouldn't open up a PR and see that the CI was failling.
Didn't know it would be so hard to re-open the PR heh.
https://github.com/isaacs/github/issues/361#issuecomment-561158372

**Comment by thesuperzapper** [comment]
@jgilme1 I will put this in my mega patch release `8.0.7` (incoming in a few min), so we dont have two releases in like 5 min

**Comment by thesuperzapper** [comment]
@jgilme1 I included this fix in `8.0.7` (and also included it for the `REDIS_PASSWORD_CMD` variable)

But please dont let it discourage you, keep contributing! 

PS: its mostly because the release process for helm charts is not crazy

**Pull request closed without merging**
