### PR TITLE
feat: allow changing pool slots on cron schedules

### PR DESCRIPTION
**Pull request by DanielMorales9**
## What does your PR do?

Introducing the scheduled pool implementation enables sync functionality to bump or reduce the number of pool slots on a specific recurrence.

### For all Pull Requests

- [x] Commits are [signed off](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#sign-your-work)
- [x] Commits have [semantic messages](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#semantic-commit-messages)
- [x] Documentation [updated](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#documentation)
- [x] Passes [ct linting](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#linting)

### For releasing ONLY

- [ ] Chart.yaml [version bumped](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#versioning)
- [ ] CHANGELOG.md updated

### CODE REVIEW

**Comment by DanielMorales9** [comment]
Hi @thesuperzapper, I would like to introduce the scheduled pools to enable scheduled autoscaling policies to the sync pools. The code is very simple just like its interface as shown below:

```
- name: "pool"
   description: "example pool with 10 slots"
   slots: 10
   schedules:
     - name: "ScaleUp"
        slots: 28
        recurrence: 0 19 * * *
     - name: "ScaleDown"
        slots: 10
        recurrence: 0 6 * * *

```

**Review by thesuperzapper — CHANGES_REQUESTED** [review]
@DanielMorales9 This is an interesting idea, but it needs more discussion.

I think we can remove the need for the global variables, while also making the behavior more stable by making a change to your logic.

The main goal I want to achieve is that even if we are not "at a scheduled update time" we should revert to the `slot_count` that would have been most recently applied (if someone makes a manual change in the UI we should revert it at the next sync, for example).

We can do this by using the `croniter.get_prev()` function on each of the defined schedules at each sync using the current time as the `start_time`, and applying the schedule with the most recent previous time.

For example:

```python
croniter(expr_format="0 12 * * *", start_time=datetime.now()).get_prev(ret_type=datetime)
```

This approach means we have no state to hold, and there is no ambiguity at the first sync about which schedule to use. Also note, in this approach the non-schedule `slots` defined in the user's values will never be applied.

**Comment by DanielMorales9** [comment]
Hi @thesuperzapper could you take another look at the PR?
Thank you

**Review by thesuperzapper — APPROVED** [review]
@DanielMorales9 thanks for your patience, I will be including this in the `8.7.0` chart release today!

Also, I have pushed a commit to your branch with some changes and docs in preparation for this.

**Review by thesuperzapper — APPROVED** [review]

**Pull request merged**
