### PR TITLE
add option to run airflow upgradedb in init-container

### PR DESCRIPTION
**Pull request by bgaechter**
Signed-off-by: Benny Gächter <benny.gaechter@gmail.com>

**What issues does your PR fix?**

None

**What does your PR do?**

Enables the use of `airflow upgradedb` as an init-container which allows airflow state database upgrades and is the prefered method of creating the airflow state database in production environments.

## Checklist

- [x] Commits are [signed](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#sign-your-work)
- [x] Commits are [squashed](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#squash-commits) (if appropriate)
- [x] Chart [version bumped](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#versioning)
- [x] Passes [linting](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#linting)

### CODE REVIEW

**Comment by gsemet** [comment]
look good to me, @thesuperzapper do you also agree?

**Comment by thesuperzapper** [comment]
@bgaechter are you able to run `upgradedb` (even if you have never run `initdb`)?

If so, we should probably just get rid of the `initdb` code path and default to `upgradedb`/`db upgrade`

What are your thoughts?

**Comment by bgaechter** [comment]
@thesuperzapper Yes, `upgradedb` will create all tables needed for airflow to run but without some default values.

Dropping `initdb` in favour of `upgradedb` would be fine by me. I am not sure what the use case is to have these default values created by `initdb`.

Should I change the code?

**Comment by thesuperzapper** [comment]
@bgaechter I think so

Lets keep the old values names of `scheduler.initdb` and `scheduler.preinitdb` (so we don't have to make a major version bump), and just update the docstrings/readme to say it will use `airflow upgradedb`

You will have to make the change in two places:
1. the startup command for the airflow-scheduler Deployment
2. the `preinit-db.sh` script in the airflow-scripts ConfigMap

Also, please add a new section to UPGRADE.md, see here for a guide:
https://github.com/airflow-helm/charts/blob/main/CONTRIBUTING.md#documentation

**Review by thesuperzapper — CHANGES_REQUESTED** [review]
I thought we agreed to leave the old value of `scheduler.initdb`?

I don't want to remove/rename values, as that will require us to bump a MAJOR version.

NOTE: if you haven't finished the PR yet, disregard this.

**Comment by bgaechter** [comment]
Okay, i think i misunderstood.

I thought you wanted to keep `airflow.initdb` and `airflow.preinitdb` but let them run `airflow upgradedb` as it gives essentially the same result (minus extra config values). This should only require a minor version bump as I did not remove or rename a value. I only changed their behaviour. And I added `airflow.upgradedb` as a separate option. Which is what my change does at the moment.

So should i revert the changes to `airflow.initdb` and `airflow.preinitdb` and only add `airflow.upgradedb` as a new value?

**Comment by thesuperzapper** [comment]
@bgaechter sorry, what I meant is that we change the behaviour of the `scheduler.initdb` and `scheduler.preinitdb` values to use `upgradedb` rather than `initdb`, but keep the same value names.

**Comment by thesuperzapper** [comment]
@bgaechter any updates?

**Comment by thesuperzapper** [comment]
This feature was implemented in https://github.com/airflow-helm/charts/pull/39

**Pull request closed without merging**
