### PR TITLE
feat: allow Secrets/ConfigMaps in `airflow.{users,connections,pools,variables}`

### LINKED ISSUE #183: Use env. variable in connections
Is it possible to use env. variables from ConfigMap in the connections ? What would be the best solution for this ?

```
  connections:
    - id: s3_logs
      type: s3
      extra: |
        {
          "aws_access_key_id": "$AWS_S3_LOGS_ACCESS_KEY_ID",
          "aws_secret_access_key": "$AWS_S3_LOGS_SECRET_ACCESS_KEY"
        }
```

### LINKED ISSUE #219: Support setting environment variables in variables.yaml from secrets and config maps
I would like to request support of secrets in the environment variables set:
Currently, it's possible to set only string value to the key:
`- key: "var_1"
    value: "my_value_1"`

Nice to have:
`variables:
    - name: var_1
      valueFrom:
         secretKeyRef:
            key: var-1-secret
            name: some-secrets`

When I do it now I get error:
`Error: execution error at (airflow/templates/jobs/secret-job-scripts.yaml:255:16): each `value` in `airflow.variables` must be non-empty!`

### LINKED ISSUE #260: use Secrets & ConfigMaps in `airflow.{connections, pools, users, variables}` definitions
Currently, users are limited to defining connections/pools/users/variables in plain-text using the `airflow.{connections, pools, users, variables}` values.

There are some significant issues with our current [Job based approach](https://github.com/airflow-helm/charts/tree/airflow-8.3.2/charts/airflow/templates/jobs):
1. any sensitive content is stored in plain-text within the users `values.yaml`
2. users must re-deploy the chart to update connections 
    - that is, they aren't dynamically syncable from an external secret manager
3. if connections are manually updated in the Airflow WebUI, they are not reverted until the next `helm install` (assuming `airflow.connectionsUpdate = true`)
    - it would be better if changes were immediately reverted, so a user does not make a change, then forget about it, only to have it undone in a week or two (when they have forgotten).

One idea is to allow `extraEnv` to be passed to each job (proposed in issue https://github.com/airflow-helm/charts/issues/183). However, because of __issue 2__ above, connections will only be updated/synced on `helm upgrade`, meaning users may not realise that the connections which used Secrets __will not be updated__ if the Secret value changes.

---

I think a sensible values structure for referencing values from Secrets/ConfigMaps in `airflow.connections` is as follows:

```yaml
airflow:
  # can reference `airflow.connectionsTemplates` keys with bash-like syntax
  connections:
    - id: my_gcp
      type: google_cloud_platform
      description: my GCP connection
      login: $GCP_USERNAME
      extra: |-
        { "extra__google_cloud_platform__keyfile_dict": "${GCP_PASSWORD}" }

  # definitions of were to get Secrets/ConfigMap values
  connectionsTemplates:
    GCP_PASSWORD:
      kind: secret
      name: my-secret
      key: password
    GCP_USERNAME:
      kind: configmap
      name: my-configmap
      key: username

  # if "true" : we perpetually sync connections
  #     - updating if Secrets/ConfigMaps change
  #     - reverting changes from WebUI
  # if "false": we only create new connections
  #     - leaving any with the same `id` as they are (allows updating in WebUI)
  connectionsUpdate: true
```

To achieve this we can create a new `connections-sync` Deployment, which is simply a Python container, with the keys of `airflow.connectionsTemplates` mounted as volumes. The Python script would perpetually check for changes in the Secretes/ConfigMaps, and from the WebUI. If changes are detected, it will bring the defined connections back to their proper value.

Obviously, we can do similar for pools, users, and variables.

### PR DESCRIPTION
**Pull request by thesuperzapper**
**What issues does your PR fix?**
- resolves #260
- fixes #183
- partially resolves the following (all jobs except `upgrade-db` have been replaced):
    - #130
    - #156
    - #141
    - #241
- superceeds the following PRs:
    - #186  
    - #146
    - #140

**What does your PR do?**

- Implements the changes proposed in:
   - #260
- Adds new values:
    - `airflow.usersTemplates`
    - `airflow.connectionsTemplates`
    - `airflow.variablesTemplates`
    - `airflow.sync`:
      - `airflow.sync.resources`
      - `airflow.sync.nodeSelector`
      - `airflow.sync.affinity`
      - `airflow.sync.tolerations`
      - `airflow.sync.securityContext`
      - `airflow.sync.podLabels`
      - `airflow.sync.annotations`
      - `airflow.sync.podAnnotations`
      - `airflow.sync.safeToEvict`

## Checklist

- [X] Commits are [signed](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#sign-your-work)
- [X] Commits are [squashed](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#squash-commits) (only do this if appropriate)
- [ ] Chart [version bumped](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#versioning) (only do this if releasing a new version)
- [X] Chart [documentation updated](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#documentation)
- [X] Passes [linting](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#linting)

### CODE REVIEW

**Comment by demetrioi** [comment]
Sound's like the new version is aware of the --debug flag. Even if i set the --debug flag I cannot see the installation details.

The debug flag works fine in the 8.3.2 version

**Comment by thesuperzapper** [comment]
@demetrioi can you explain what you mean, in a new issue (rather than on this PR, unless I am mistaken about its relationship to this PR)?

**Comment by demetrioi** [comment]
Sorry @thesuperzapper. It was a typo in my helm values. It's working fine. Thanks.

**Comment by aprettyloner** [comment]
@thesuperzapper Are all these `snyc` typos that will be fixed?

**Comment by thesuperzapper** [comment]
@aprettyloner thanks for finding that!

I have raised the issue https://github.com/airflow-helm/charts/issues/364 to resolve those typos (note they are purely cosmetic, and will not impact the charts behaviour).

**Pull request merged**
