### PR TITLE
Allow local development with Skaffold

### PR DESCRIPTION
**Pull request by CapChrisCap**
**What issues does your PR fix?**

- allows developers to use this chart with Skaffold for local development

**What does your PR do?**

Skaffold can also build local docker images, deploy helm charts in any (e.g. local) Kubernetes cluster including file syncs. This allows developers to sync their airflow dags directly in the pods. For that, the docker image built by Skaffold needs to be referenced for the KubernetesExecutor. 

The following additional code inside of the `configmap-env.yaml` file is required because Skaffold can otherwise not inject the created docker image with the DAG live-reload inside of the workers: 

```
  {{- if (not .Values.airflow.config.AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY) }}
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: {{ .Values.airflow.image.repository }}
  {{- end }}
  {{- if (not .Values.airflow.config.AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG) }}
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: {{ .Values.airflow.image.tag }}
  {{- end }}
```

In addition, I also added an example to explain how to make Skaffold running with this helm chart. 

## Checklist

- [x] Commits are [signed](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#sign-your-work)
- [ ] Commits are [squashed](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#squash-commits) (if appropriate)
- [x] Chart [version bumped](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#versioning)
- [x] Chart [documentation updated](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#documentation)
- [x] Passes [linting](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#linting)

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@CapChrisCap, I am not familiar with Scaffold, who would be using it, and for what? (within the context of this chart)

Also, I am not sure we should put docs for it in the chart itself (a Medium post might be better), but if we can fix something in the ConfigMap to make it work for people,  I am not against that.

**Comment by CapChrisCap** [comment]
Thanks for checking my pull request @thesuperzapper . I had the same feeling that it might be better in an own blog post but I just added it if it might be useful. But I removed the examples folder. 

Regarding your question: Skaffold is used by Developers that are developing hooks, tasks, dags or plugins for their jobs. They want to develop their code inside of a local Kubernetes Cluster, where the code is directly injected in the pods. This is where [Skaffold](https://skaffold.dev/) useful because it automatically builds, syncs and deploys your code into your cluster. There are also other tools that can do that but Skaffold is one of the most popular Local Kubernetes Development Tool. 

The changes I did were required because otherwise, I can not inherit the image value property into `AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY` and `AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG`. 

PS: I have no idea why the CI pipeline is now failing, I actually only removed the examples folder :-O

**Comment by thesuperzapper** [comment]
@CapChrisCap 

Please also update the docstring of `airflow.executor`: https://github.com/airflow-helm/charts/blob/airflow-7.14.0/charts/airflow/values.yaml#L23

To say that we also set `AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME`, `AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY`, `AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG`.

__NOTE:__ you currently are only setting these variables if `airflow.executor` = `KubernetesExecutor`

**Comment by CapChrisCap** [comment]
@thesuperzapper I updated the docstrings.
Due to your note: I know that the changes only apply for the K8s Executor. I do not use the `CeleryExecutor` in production and can therefore not ensure that really everything works. If someone has the same issues I had for the CeleryExecutor, my changes can also be applied to the `CeleryExecutor`.

**Review by thesuperzapper — APPROVED** [review]
Looks good now

**Pull request merged**
