### PR TITLE
run jobs with airflow serviceAccount

### PR DESCRIPTION
**Pull request by moskitone**
Signed-off-by: Volodymyr Moseichuk <moskitone@gmail.com>

**What does your PR do?**

Jobs (helm-hooks) will run with the same serviceAccount as other pods.

## Checklist

- [x] Commits are [signed](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#sign-your-work)
- [x] Commits are [squashed](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#squash-commits) (if appropriate)
- [x] Chart [version bumped](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#versioning)
- [x] Chart [documentation updated](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#documentation)
- [x] Passes [linting](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#linting)

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@moskitone can you think of something which this fixes?

**Comment by moskitone** [comment]
> @moskitone can you think of something which this fixes?

We got into issue with Vault and dynamic provisioning of database credentials.
We use Hashicorp Vault and https://banzaicloud.com/docs/bank-vaults/mutating-webhook/ to deliver credentials into pods. Due to security reasons we allowed only one kubernetes serviceAccount to read from vault. 
So we expected that every pod will run under one serviceAccount created by this helm chart, but helm hooks use the **default** one.
This PR fixes that case.
Should I open github issue?

**Comment by moskitone** [comment]
@thesuperzapper could you please check?

**Comment by thesuperzapper** [comment]
@moskitone thanks for the PR, I just rebased it to make it version `8.1.2`

**Pull request merged**
