### PR TITLE
add "Release"  to template context dict

### LINKED ISSUE #116: Latest version: nil pointer on .Release.Name
**What is the bug?**

When using the latest version released for Airflow 2 (v8.0.2), and using the `template` command, I obtain a nil exception on .Release.Name

```
Error: UPGRADE FAILED: template: airflow/charts/airflow/templates/worker/worker-statefulset.yaml:170:22: executing "airflow/charts/airflow/templates/worker/worker-statefulset.yaml" at <include "airflow.volumes" (dict "Values" .Values "extraPipPackages" $extraPipPackages "extraVolumes" $extraVolumes)>: error calling include: template: airflow/charts/airflow/templates/_helpers/pods.tpl:238:19: executing "airflow.volumes" at <include "airflow.fullname" .>: error calling include: template: airflow/charts/airflow/templates/_helpers/common.tpl:6:24: executing "airflow.fullname" at <.Release.Name>: nil pointer evaluating interface {}.Name
helm.go:94: [debug] template: airflow/charts/airflow/templates/worker/worker-statefulset.yaml:170:22: executing "airflow/charts/airflow/templates/worker/worker-statefulset.yaml" at <include "airflow.volumes" (dict "Values" .Values "extraPipPackages" $extraPipPackages "extraVolumes" $extraVolumes)>: error calling include: template: airflow/charts/airflow/templates/_helpers/pods.tpl:238:19: executing "airflow.volumes" at <include "airflow.fullname" .>: error calling include: template: airflow/charts/airflow/templates/_helpers/common.tpl:6:24: executing "airflow.fullname" at <.Release.Name>: nil pointer evaluating interface {}.Name
UPGRADE FAILED
main.newUpgradeCmd.func2
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:156
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:93
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373
```

The command I I use is:
```
helm3 template airflow [... options]
```
The dependency on Release.Name has been introduced in the version 8.0.0

Note:
I have also tried `helm3 template airflow airflow [... options]` (to give an explicit name)

### PR DESCRIPTION
**Pull request by meseta**
Signed-off-by: Yuan Gao <meseta@gmail.com>

**What issues does your PR fix?**

- fixes #116 

**What does your PR do?**

Resolves the error "nil pointer evaluating interface {}.Name" when providing sshKnownHosts, which is caused by not passing the .Release object in the include context

As reported in #116, this issue also impacts using `dags.persistence.enabled: true`

## Checklist

- [x] Commits are [signed](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#sign-your-work)
- [x] Commits are [squashed](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#squash-commits) (if appropriate)
- [x] Chart [version bumped](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#versioning)
- [x] Chart [documentation updated](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#documentation)
- [x] Passes [linting](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#linting)

### CODE REVIEW

**Comment by hussainsaify** [comment]
@gsemet  @thesuperzapper Can you please review and merge this PR as it is blocking  us to upgrade airflow to 2.0?

**Comment by thesuperzapper** [comment]
@hussainsaify currently looking into it right now, am investigating an alternative fix.

Will decide very soon if this is the right approach.

In the meantime, can you rebase for `8.0.3` base?

**Comment by thesuperzapper** [comment]
@meseta just realise you are PR owner, can you rebase?

**Comment by meseta** [comment]
@thesuperzapper sure thing, have done that

**Comment by thesuperzapper** [comment]
@meseta lol, literally just did if for you, thought you were having trouble, sorry

**Comment by meseta** [comment]
heh, no worries, though your force-push overwrote the version bump I made for 8.0.3 -> 8.0.4, which looks like what's causing the lint to fail

**Comment by thesuperzapper** [comment]
feel free to amend the latest commit (undo and force push) with the 8.0.4 included

**Comment by thesuperzapper** [comment]
@meseta looks good, I just added the same fix to other template `include`'s

**Review by thesuperzapper — APPROVED** [review]
@meseta looks good, I just added the same fix to other template `include`'s

**Comment by hussainsaify** [comment]
@thesuperzapper @meseta Thanks a lot :)

**Pull request merged**
