### PR TITLE
feat/add-extraInitContainers-to-workers

### PR DESCRIPTION
**Pull request by xlagg5**
## What does your PR do?

Adds extraInitContainers section to workers.

### For all Pull Requests

- [x] Commits are [signed off](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#sign-your-work)
- [x] Commits have [semantic messages](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#semantic-commit-messages)
- [x] Documentation [updated](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#documentation)
- [x] Passes [ct linting](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#linting)

### For releasing ONLY

- [ ] Chart.yaml [version bumped](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#versioning)
- [ ] CHANGELOG.md updated

### CODE REVIEW

**Comment by dylac** [comment]
This feature would be very useful for me, can it be reviewed?

**Comment by thesuperzapper** [comment]
Bumping for bot.

**Comment by thesuperzapper** [comment]
@xlagg5 thanks for the PR, but I am going to close this in favor of https://github.com/airflow-helm/charts/pull/856

That PR adds `extraContainers` and `extraInitContainers` values for all the deployments, not just workers.

**Comment by thesuperzapper** [comment]
@xlagg5 thanks for the PR, but I am going to close this in favor of https://github.com/airflow-helm/charts/pull/856

That PR adds `extraContainers` and `extraInitContainers` values for all the deployments, not just workers.

**Pull request closed without merging**
