### PR TITLE
feat: allow labels on `sync` and `db-migrations` Deployments/Jobs

### LINKED ISSUE #447: Common Labels
Hi,

Our organization requires some specific labels to be added to every Deployment on K8s. I understand, that's not a pressing issue, but, would you be so kind to add a "CommonLabels" section to your ".../airflow/values..yaml" that'll be translated to every "label" section of the Deployment YAMLs?

### LINKED ISSUE #466: allow setting labels on `sync` and `db-migrations` Deployments/Jobs
## What is your feature request?

In some places it's possible to configure `labels` and `podLabels` via values.yaml. Somewhere only `podLables` are available. I'm suggesting to unify it all over the chart.

There are some examples of deployment templates which have only podLabels: `db-migrations-deployment.yaml`, `pgbouncer-deployment.yaml`, `sync-connections-deployment.yaml`

We are not able to migrate to latest chart version, because K8s we use require custom labels to be present on every deployment

### PR DESCRIPTION
**Pull request by oleksandrkovalenko**
## What issues does your PR fix?

- resolves https://github.com/airflow-helm/charts/issues/466
- resolves https://github.com/airflow-helm/charts/issues/447

## What does your PR do?

- Adds the following values to set labels on the `sync` and `db-migrations` Deployments/Jobs:
   - `airflow.dbMigrations.labels`
   - `airflow.sync.labels`
- Fixed the `pgbouncer.labels` value so that it is respected

### For all Pull Requests

- [x] Commits are [signed off](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#sign-your-work)
- [x] Commits have [semantic messages](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#semantic-commit-messages)
- [x] Documentation [updated](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#documentation)
- [x] Passes [ct linting](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#linting)

### For releasing ONLY

- [ ] Chart.yaml [version bumped](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#versioning)
- [ ] CHANGELOG.md updated

### CODE REVIEW

**Review by thesuperzapper — CHANGES_REQUESTED** [review]
@oleksandrkovalenko thanks for the PR!

However, you have missed a adding the labels to the Job resources:
- https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/db-migrations/db-migrations-job.yaml
- https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/sync/sync-connections-job.yaml
- https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/sync/sync-pools-job.yaml
- https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/sync/sync-users-job.yaml
- https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/sync/sync-variables-job.yaml

Can you please add the labels to these resources also?

**Comment by oleksandrkovalenko** [comment]
@thesuperzapper I just make the changes. Could you please check them

**Comment by oleksandr-blacklane** [comment]
Could somebody please take a look at this one. The issue was already marked as staled. Sorry, I just afraid it will be forgotten. Many thanks

**Comment by oleksandrkovalenko** [comment]
Could somebody please take a look at this one. The issue was already marked as staled. Sorry, I just afraid it will be forgotten. Many thanks

**Review by thesuperzapper — DISMISSED** [review]
@oleksandrkovalenko thanks for the PR, it looks good-to-go for the `8.6.0` release, I will put it in "ready to merge", and merge it just before we cut the release.

**Pull request merged**
