### PR TITLE
fix: ensure git-sync is the first init-container

### LINKED ISSUE #276: ensure git-sync is the first init-container
We created PR https://github.com/airflow-helm/charts/pull/255 to resolve the possibility of users storing plugins in their git-sync repo, causing the `check-db` to fail.

Init-containers are run [in the order they are declared](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#detailed-behavior), so if the `git-sync` init-container is not declared first, the plugins will not exist when `check-db` runs, leading to a CrashLoopBackoff.

__We should order the init-containers so that `git-sync` is first init-container.__

### PR DESCRIPTION
**Pull request by bradarndt**
Signed-off-by: Brad Arndt <barndt@trueaccord.com>

**What issues does your PR fix?**

- fixes #276 

**What does your PR do?**

sets the git-sync container as the first init container

## Checklist
- [X] Commits are [signed](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#sign-your-work)
- [X] Commits are [squashed](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#squash-commits) (only do this if appropriate)
- [X] Chart [version bumped](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#versioning) (only do this if releasing a new version)
- [X] Chart [documentation updated](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#documentation)
- [X] Passes [linting](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#linting)

### CODE REVIEW

**Comment by bradarndt** [comment]
@gsemet @thesuperzapper - apologies for the direct call out, but could you let me know if there's anything additional needed to request a review on this?  I've already performed all of the steps listed in the contributing checklist.  I'm a first-time contributor to this repo, so just wanted to make sure I wasn't missing anything.  Thanks!

**Comment by gsemet** [comment]
Hi. thanks for you contribution. Look good, I let @thesuperzapper allow the merge.

**Comment by bradarndt** [comment]
> Hi. thanks for you contribution. Look good, I let @thesuperzapper allow the merge.

Great!  Thanks!!

**Comment by thesuperzapper** [comment]
@bradarndt thanks for the PR!

Sadly, this is no longer needed as PR https://github.com/airflow-helm/charts/pull/390 has superseded it.

Please don't let this discourage you from contributing in the future, as you have helped lots!

**Pull request closed without merging**
